name: test

on: [workflow_dispatch, push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: IPFS2.eth Resolver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge install foundry-rs/forge-std --no-commit --no-git
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test --fork-url https://rpc.ankr.com/eth_goerli -vvv --fork-block-number 8897000
        id: test
          
      - name: Set name of badge
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "checks"
          replace: "Status"
          include: ".github/badge.svg"
          regex: false
      
      - name: Capitalise test status
        run: |
          echo "STATUS=$(echo "${{ steps.test.outcome }}," | sed 's/\b./\U&/')" >> ${GITHUB_ENV}
          
      - name: Set status of Forge tests
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "status"
          replace: "${{ env.STATUS }}"
          include: ".github/badge.svg"
          regex: false
          
      - name: Set color of outcome
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "3C1"
          replace: "F73"
          include: ".github/badge.svg"
          regex: false
        if: steps.test.outcome == 'failure'
        
      - name: Commit changes to .github/badge.svg
        uses: EndBug/add-and-commit@v8
        with:
          author_name: sshmatrix
          author_email: cryptosauron@protonmail.com
          message: Update badge.svg
          add: '.github/badge.svg'
          
      - name: Push changes to .github/badge.svg
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          force: true
          github_token: ${{ secrets.TOKEN }}
          
