name: test

on: [workflow_dispatch, push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: IPFS2.eth Resolver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge install foundry-rs/forge-std --no-commit --no-git
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test --fork-url https://rpc.ankr.com/eth_goerli -vvv --fork-block-number 8897000
        id: test
        
      - name: Create badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 645156b2698bd776f38636d6dad5ead0
          filename: badge.json
          label: Checks
          message: Status
          color: orange
          
      - name: Set name of badge
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "checks"
          replace: "Status"
          include: ".github/badge.svg"
          regex: false
      
      - name: Capitalise test status
        run: |
          echo "STATUS=$(echo "${steps.test.outcome,,}" | sed 's/\b./\U&/')" >> ${GITHUB_ENV}
          
      - name: Set status of Forge tests
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "status"
          replace: "${STATUS}"
          include: ".github/badge.svg"
          regex: false
          
      - name: Set color of outcome
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "3C1"
          replace: "F73"
          include: ".github/badge.svg"
          regex: false
        if: steps.test.outcome == 'failure'
          
      - name: Deploy Badge to Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_SECRET }}
          gist_id: 057d4cd05f99586abf22a3cb14f40ff6
          file_path: .github/badge.svg
          file_type: text
