name: test

on: [workflow_dispatch, push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge install foundry-rs/forge-std --no-commit --no-git
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test --fork-url https://rpc.ankr.com/eth_goerli -vvv --fork-block-number 8897000
        id: test
        
      - name: Create Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 645156b2698bd776f38636d6dad5ead0
          filename: badge.json
          label: Hello
          message: World
          color: orange
          
      - name: Replace Text in Gist
        run: |
          content=$(curl -H "Authorization: token ${{ secrets.GIST_SECRET }}" https://api.github.com/gists/057d4cd05f99586abf22a3cb14f40ff6 | jq -r '.files["badge.svg"].content')
          new_content=$(echo "$content" | sed 's/checks/tests/g' | sed 's/status/pass/g')
          curl -H "Authorization: token ${{ secrets.GIST_SECRET }}" --data-binary "{\"files\": {\"badge.svg\": {\"content\": \"$new_content\"}}}" https://api.github.com/gists/057d4cd05f99586abf22a3cb14f40ff6 -X PATCH
